-- =====================================================================
-- ESQUEMA CANÓNICO de Supabase para aprendizaje-app
-- Aplicado y VERIFICADO el 2026-06-15 en el proyecto nuevo
-- (tras perderse el proyecto anterior, pausado >90 días sin datos de usuario).
--
-- Reemplaza a los .sql sueltos antiguos de /docs (que estaban desactualizados:
-- p.ej. usaban `categoria` en vez de `categorias text[]`).
--
-- Modo "sin login": RLS activado en todas las tablas con política pública
-- (using(true) with check(true)) para que la app funcione con la anon key.
-- Ejecutar en: Supabase Dashboard > SQL Editor (o vía migración).
-- =====================================================================

-- Función reutilizable para mantener updated_at
create or replace function update_updated_at_column()
returns trigger as $$
begin new.updated_at = now(); return new; end;
$$ language plpgsql;

-- ===================== HABILIDADES =====================
create table if not exists habilidades (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  nombre text not null,
  categoria text,                       -- legacy (no usado por el código actual)
  categorias text[] default '{}',       -- usado por el código actual (array de categorías)
  nivel_percibido text,                 -- usado por el código actual
  descripcion text,
  guia_generada text,
  tiempo_total_segundos integer default 0,
  nivel text default 'novato',
  experiencia_previa text default 'ninguna',
  objetivo_semanal_minutos integer default null,
  deleted_at timestamptz default null,  -- soft delete (papelera)
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists sesiones_practica (
  id uuid primary key default gen_random_uuid(),
  habilidad_id uuid references habilidades(id) on delete cascade,
  duracion_segundos integer not null,
  resumen text,
  fecha timestamptz default now()
);

-- ===================== HABITS =====================
create table if not exists habits (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  text text not null,
  category text default 'other',
  streak integer default 0,
  with_notification boolean default true,
  notification_time text,               -- deprecated, backwards compat
  notification_times text[],            -- array de horas "HH:MM"
  custom_message text,
  telegram_chat_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists habit_logs (
  id uuid primary key default gen_random_uuid(),
  habit_id uuid references habits(id) on delete cascade,
  completed_at date not null,
  created_at timestamptz default now(),
  unique(habit_id, completed_at)
);

-- ===================== RECORDATORIOS =====================
create table if not exists recordatorios (
  id uuid primary key default gen_random_uuid(),
  habilidad_id uuid references habilidades(id) on delete cascade,
  dia_semana integer not null check (dia_semana between 0 and 6),  -- 0=Dom..6=Sab
  hora time not null,
  email_enabled boolean default true,
  active boolean default true,
  created_at timestamptz default now()
);

-- ===================== CHATS (tutor) =====================
create table if not exists chats (
  id uuid primary key default gen_random_uuid(),
  titulo text,
  tema text,
  estado text default 'abierto',
  conversacion_json jsonb,
  created_at timestamptz default now()
);

create table if not exists chat_mensajes (
  id uuid primary key default gen_random_uuid(),
  chat_id uuid references chats(id) on delete cascade,
  rol text not null,                    -- 'usuario' | 'ia'
  texto text not null,
  created_at timestamptz default now()
);

-- ===================== EXAM HISTORY (test semanal) =====================
create table if not exists exam_history (
  id uuid primary key default gen_random_uuid(),
  score numeric,
  total_questions integer,
  questions_data jsonb,
  created_at timestamptz default now()
);

-- ===================== APRENDIZAJES (sync Supabase; localStorage es la fuente actual) =====================
create table if not exists aprendizajes (
  id bigint generated by default as identity primary key,
  sector_id integer,
  user_id uuid,
  titulo text not null,
  contenido text,
  resumen text,
  conversacion_json jsonb,
  deleted_at timestamptz default null,
  created_at timestamptz default now()
);

create table if not exists sectores (
  id integer primary key,
  nombre text not null,
  icono text,
  color text,
  created_at timestamptz default now()
);

create table if not exists progreso (
  id bigint generated by default as identity primary key,
  sector_id integer,
  created_at timestamptz default now()
);

-- ===================== ÍNDICES =====================
create index if not exists idx_habilidades_user on habilidades(user_id);
create index if not exists idx_sesiones_habilidad on sesiones_practica(habilidad_id);
create index if not exists idx_habits_user on habits(user_id);
create index if not exists idx_habits_chat_id on habits(telegram_chat_id);
create index if not exists idx_habit_logs_habit on habit_logs(habit_id);
create index if not exists idx_habit_logs_date on habit_logs(completed_at);
create index if not exists idx_recordatorios_dia_hora on recordatorios(dia_semana, hora);
create index if not exists idx_recordatorios_habilidad on recordatorios(habilidad_id);
create index if not exists idx_chat_mensajes_chat on chat_mensajes(chat_id, created_at);
create index if not exists idx_aprendizajes_sector on aprendizajes(sector_id);

-- ===================== TRIGGERS updated_at =====================
drop trigger if exists update_habilidades_updated_at on habilidades;
create trigger update_habilidades_updated_at before update on habilidades
  for each row execute function update_updated_at_column();
drop trigger if exists update_habits_updated_at on habits;
create trigger update_habits_updated_at before update on habits
  for each row execute function update_updated_at_column();

-- ===================== RLS: acceso público (modo sin login) =====================
do $$
declare t text;
begin
  foreach t in array array['habilidades','sesiones_practica','habits','habit_logs','recordatorios','chats','chat_mensajes','exam_history','aprendizajes','sectores','progreso']
  loop
    execute format('alter table %I enable row level security;', t);
    execute format('drop policy if exists %I on %I;', 'public_all_'||t, t);
    execute format('create policy %I on %I for all using (true) with check (true);', 'public_all_'||t, t);
  end loop;
end $$;
